### ISSUE TITLE
ทดสอบก่อนรายงานความคืบหน้า

### ISSUE THREAD

**Issue by KoMoRee** [PanatKaewlangka/17#11]

**Comment by PanatKaewlangka** [comment]
-ระบบดึงบาร์สมบูรณ์(เพิ่มให้บาร์เขียวด้านบนลดลงได้)
-หน้าmenuเสร็จแล้ว
-ระบบคลิกรัวๆเสร็จแล้ว
-ด่าน1 เหลือสอนการเล่น
-ด่าน2 -
-ด่าน3 -
-มินิเกมยังไม่สมบูรณ์
-ปลาน้ำจืด 9 ตัว
-ปลาน้ำเค็ม 7 ตัว
-มังกรน้ำ เป็นตัวพิเศษ mini game(ยังไม่สมบูรณ์)
-แอเรียล บอสตัวสุดท้าย
-กราฟฟิคปลาวิ่งในน้ำ(ยังไม่สมบูรณ์)
-แอนิเมชั่นตัวละคร(ยังไม่สมบูรณ์)
-เพิ่มคำอธิบายปลาแต่ละตัว
