### ISSUE TITLE
ทดสอบครั้งสุดท้าย

### ISSUE THREAD

**Issue by KoMoRee** [PanatKaewlangka/17#12]

**Comment by PanatKaewlangka** [comment]
เมื่อตกปลาเสร็จกดกลับ แล้วขึ้นหน้าแอเรียล
เมื่อไม่คลิกป๊อบจนหมดหลอด ปลาไม่หลุด

**Comment by PanatKaewlangka** [comment]
เบ็ดตกปลาซื้อไม่ได้ + อันแรกซื้อแล้วบัค

**Comment by PanatKaewlangka** [comment]
เมื่อเปลี่ยนด่าน แล้วบัคฉากสลับ และบาร์ไม่ขึ้น

**Comment by PanatKaewlangka** [comment]
ไปด่านต่อไปไม่ได้
