### ISSUE TITLE
(กราฟฟิก) ปลาบ่อแรก

### ISSUE THREAD

**Issue by KoMoRee** [PanatKaewlangka/17#13]
1.รูปปลา
2.ชื่อ
3.รายละเอียด

**Comment by KoMoRee** [comment]
![images - 2023-08-30T142646.531.jpeg](https://github.com/PanatKaewlangka/17/assets/82720850/e640f21e-3e7f-4e86-9060-1f510582d71f)

![images - 2023-08-30T142630.922.jpeg](https://github.com/PanatKaewlangka/17/assets/82720850/b6b90a85-8f66-47ff-86ce-bd9d7efaa9de)

![images - 2023-08-30T142608.596.jpeg](https://github.com/PanatKaewlangka/17/assets/82720850/4800cc1a-612e-4252-a7cb-b691a7377de4)

![images - 2023-08-30T142552.879.jpeg](https://github.com/PanatKaewlangka/17/assets/82720850/3525e1d7-1f6c-4093-b7dc-827038310cf9)

![images (99).jpeg](https://github.com/PanatKaewlangka/17/assets/82720850/409d513a-f4ea-411a-b549-d1bbbea6df8f)

![images (98).jpeg](https://github.com/PanatKaewlangka/17/assets/82720850/59689749-bd5b-4898-9e90-ce9e416733ef)

![images (96).jpeg](https://github.com/PanatKaewlangka/17/assets/82720850/59587f65-e313-4c8f-9242-be8bbe32fa06)

![images (95).jpeg](https://github.com/PanatKaewlangka/17/assets/82720850/d111a13d-6a78-4feb-8be7-91919a522960)

![images (94).jpeg](https://github.com/PanatKaewlangka/17/assets/82720850/8683780a-0ca1-4a89-a85a-5e05e3141b6b)

**Comment by eyenatchaya** [comment]
ปลาน้ำจืด
https://drive.google.com/drive/folders/1-7nBrCt0W9Zy3p1dRkzYKnufyA960_I8?usp=drive_link

**Comment by PanatKaewlangka** [comment]
https://scratch.mit.edu/projects/890230947
