### ISSUE TITLE
(กราฟฟิก) ปลาบ่อสอง

### ISSUE THREAD

**Issue by KoMoRee** [PanatKaewlangka/17#14]
1.รูปปลา
2.ชื่อ
3.รายละเอียด

**Comment by eyenatchaya** [comment]
https://docs.google.com/document/d/1UdTvx9N65617nLOSb8sAt91Tis44mgRBEM_HWqgQGDc/edit?usp=sharing

**Comment by eyenatchaya** [comment]
ถ้าเพื่อนๆอยากตั้งชื่อสามารถเข้าไปเขียนในไฟล์ Docs ได้ (สำหรับถ้าใครอยากแชร์ไอเดียอะไรพิมพ์ในนั้นได้เลยนะ)
