### ISSUE TITLE
(กราฟฟิก) ปลาบ่อสุดท้าย

### ISSUE THREAD

**Issue by KoMoRee** [PanatKaewlangka/17#15]
1.รูปปลา
2.ชื่อ
3.รายละเอียด

-มีแอเรียลด้วย

**Comment by PanatKaewlangka** [comment]
https://drive.google.com/drive/folders/1-5x2vaYqYILFAbz1TI-5SlGejHSdh_cs?usp=drive_link

**Comment by PanatKaewlangka** [comment]
เพิ่มปลาจาก5เป็น7ตัว

**Comment by PanatKaewlangka** [comment]
เพิ่มปลาพิเศษ คือ มังกรน้ำ

**Comment by PanatKaewlangka** [comment]
เพิ่มบอส คือ แอเรียล
