### ISSUE TITLE
(กราฟฟิก) ตัวละคร

### ISSUE THREAD

**Issue by KoMoRee** [PanatKaewlangka/17#16]
1.รูป
2.อนิเมชั่น
  -ตอนตกปลา
  -ตอนรอปลาติดเบ็ด
  -ตอนได้รับปลา
3.เสียงตอนตกปลา

**Comment by eyenatchaya** [comment]
ตัวละคร หน้าตรง หันข้าง
https://drive.google.com/drive/folders/13gQOn-Ps8V_SRgoYgV86l2Ygv4ZRevHl?usp=drive_link

**Comment by eyenatchaya** [comment]
https://drive.google.com/drive/folders/1--87pSmPC6yhWfVqR8kZ5kE9M_EadWON?usp=drive_link

**Comment by eyenatchaya** [comment]
https://scratch.mit.edu/projects/888576850

**Comment by eyenatchaya** [comment]
เอนิเมชั่นตัวละคร
https://scratch.mit.edu/projects/889784938

**Comment by PanatKaewlangka** [comment]
https://scratch.mit.edu/projects/889825465
ปลาขยับไปขยับมา
