### ISSUE TITLE
(ระบบ) mini game สู้กับบอส

### ISSUE THREAD

**Issue by KoMoRee** [PanatKaewlangka/17#19]

**Comment by PraeThipwarin** [comment]
ยังไม่ได้ใส่รายละเอียด
https://scratch.mit.edu/projects/888501376

**Comment by eyenatchaya** [comment]
ฉากอวกาศ
https://drive.google.com/drive/folders/1-Ag3BlwqpbPyeNbUkWb37_I-YMVkdF0x?usp=drive_link

**Comment by PraeThipwarin** [comment]
ยกเลิกระบบนี้
