### ISSUE TITLE
(กราฟฟิค) หน้าข้อมูลปลา

### ISSUE THREAD

**Issue by KoMoRee** [PanatKaewlangka/17#22]
1.ขึ้นรูปปลาที่ตกได้
2.ขึ้นข้อมูล
3.ปุ่มที่กดแล้วไปต่อ

**Comment by KoMoRee** [comment]
### Source
https://www.youtube.com/watch?v=HbVjKm5_dDw
https://www.youtube.com/watch?v=UX0oxLquAY4
https://www.youtube.com/watch?v=XqbJV8sZZXU
https://www.youtube.com/watch?v=BAy0SUnB1J0

**Comment by eyenatchaya** [comment]
ชื่อปลา + รายละเอียด
https://docs.google.com/document/d/1UdTvx9N65617nLOSb8sAt91Tis44mgRBEM_HWqgQGDc/edit?usp=sharing

**Comment by eyenatchaya** [comment]
https://drive.google.com/drive/folders/1-CESuS1-MxdbtFx4eDvOfKxoUOR7bBdZ?usp=drive_link

**Comment by PanatKaewlangka** [comment]
https://drive.google.com/file/d/1QAhEdtxEMbXSmq5RNsKm8Gn5XLWpHjKM/view?usp=drive_link

**Comment by PanatKaewlangka** [comment]
https://drive.google.com/drive/folders/1-8RQ4DJ1AusCJLr_secpb-GqbAOIbJDw?usp=drive_link
