### ISSUE TITLE
(กราฟฟิค) จัดองค์ประกอบหน้าตาเกม เสียง

### ISSUE THREAD

**Issue by KoMoRee** [PanatKaewlangka/17#24]

**Comment by eyenatchaya** [comment]
ฉากชนะเกม
https://drive.google.com/drive/folders/1-KFuSCNOXU7iqX78GyYfr-_I4VbWKqy3

**Comment by PanatKaewlangka** [comment]
https://drive.google.com/drive/folders/1SGZGX42Knp-vtiMXC4e4MqBaSSHP_y--?usp=sharing

**Comment by eyenatchaya** [comment]
เสียงเดินตัวละคร
https://drive.google.com/drive/folders/1kFoP135x50SWWGj8D5lbtWUoiBPbfsm9?usp=drive_link

**Comment by PanatKaewlangka** [comment]
https://drive.google.com/file/d/1HmuZoME_29OYUrWIQVjuk9nGr9GhZEiX/view?usp=sharing
