### ISSUE TITLE
(ระบบ) หน้าMenu

### ISSUE THREAD

**Issue by KoMoRee** [PanatKaewlangka/17#4]
ปุ่ม
-start
-buy
-เล่นอีกรอบ

**Comment by KoMoRee** [comment]
### Source
ตัวอย่างการสร้างปุ่ม
https://www.youtube.com/watch?v=0H_L7HiZoyU
https://www.youtube.com/watch?v=sbzZfMC0nXQ
https://www.youtube.com/watch?v=7II-EpaxBEI

**Comment by PraeThipwarin** [comment]
ตัวปุ่ม
https://scratch.mit.edu/projects/888803827

รูปปุ่มที่ใช้
https://drive.google.com/drive/folders/1JwJLiUwa0e9Kdvh678-0pNqszCo4E5cI?usp=drive_link

**Comment by PanatKaewlangka** [comment]
https://drive.google.com/file/d/1cUMcjZicYk55SWBf6fCyeRO0DBAWP0gv/view?usp=sharing
