### ISSUE TITLE
(ระบบ) ดึงบาร์เขียว

### ISSUE THREAD

**Issue by KoMoRee** [PanatKaewlangka/17#5]
### 1.ปลาขยับไปมาแบบสุ่มภายในช่อง
  -ขยับสมูท
  -เพิ่ม-ลดความเร็วได้
### 2.แท่นที่ผู้เล่นต้องควบคุม
  -ถ้าปล่อยไว้แท่นจะตกลง
  -ถ้าผู้เล่นกดแท่นจะเลื่อนขึ้น
  -เลื่อนแบบมีความร่ง(optional)
  -สามารถเพิ่มลดความเร็วการขยับได้
  -สามารถเพิ่มลดความยาวแท่นได้(สำหรับปรับความยากง่าย)
  -เมื่อแท่นชนขอบเร็วให้มีการกระเด้ง(optional)
### 3.บาร์เขียว (สำหรับบอกว่าใกล้เสร็จหรือยัง)
  -บาร์จะขยับขึ้นเมื่อแท่นสัมผัสกับปลา
  -บาร์จะขยับลงเมื่อแท่นไม่สัมผัสกับปลา
 
-เริ่มต้นให้บาร์แท่นและปลาอยู่ตรงกลาง

**Comment by KoMoRee** [comment]
### Source
สร้างบาร์เขียว
https://youtu.be/dtMy3umcoEI?si=nippmCX0qySlXb11
https://youtu.be/Faf6NelRMA8?si=IsJq-4BhJH6Jtbul
https://youtu.be/fm9QJ9yk1jw?si=jG5XJZnCVLRLma0Z

ระบบความเร่ง
https://www.youtube.com/watch?v=Rg_UIn5vii8

เกี่ยวกับบล็อคคำสั่ง Clone
https://youtu.be/rQsMSamqDvM?si=idgtz0uPyk7AVM99

**Comment by KoMoRee** [comment]
### Code
**บาร์เขียว (prototype)**
https://scratch.mit.edu/projects/888040177

**บาร์เขียวกับแท่น ver.1**
https://scratch.mit.edu/projects/888066777
-ขนาดปลาไม่เกิน12pixel
-ขอบกรอบแท่น(ด้านละ)4pixel
-แท่นยาว16pixel (4x4ช่อง)

**บาร์เขียว+แท่นเลื่อน+ปลา**
https://scratch.mit.edu/projects/889268077
-ต้องคลิ๊กธงประมาณ2-3ทีถึงจะเริ่มเล่นใหม่ได้
-กด space bar เพื่อควบคุมแท่นเลื่อน
-ถ้าชนะspriteจะย่ำอยู่กับที่
-ถ้าแพ้spriteจะเดินออกไป

**(ล่าสุด) บาร์เขียว+แท่นเลื่อน+ปลา**
https://scratch.mit.edu/projects/889645439

**Comment by PanatKaewlangka** [comment]
บาร์เขียวทะลุเลยขอบออก
