### ISSUE TITLE
(ระบบ) คลิ๊กรัวๆ

### ISSUE THREAD

**Issue by KoMoRee** [PanatKaewlangka/17#6]

**Comment by KoMoRee** [comment]
### Source
https://www.youtube.com/watch?v=4v1CIKehF6E
https://www.youtube.com/watch?v=Rm8nFve64KE
https://www.youtube.com/watch?v=R38_FxQ3VgA
https://www.youtube.com/watch?v=WhLJno3uJdQ
https://www.youtube.com/watch?v=LpRiLlcXZRE

**Comment by PraeThipwarin** [comment]
ยังไม่ได้ใส่รายละเอียด
https://scratch.mit.edu/projects/888799209

**Comment by KoMoRee** [comment]
### Code
**Wave**
https://scratch.mit.edu/projects/889636801
